global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'wearipedia-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules.yml